services:
  mysql:
    image: mysql:latest
    container_name: dreamShopDBContainer
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=dreamShopDB
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: